package com.tenshun.cache.generators;

/**
 * 04.05.2017.
 */
public abstract class Generator {
    /**
     * Generate the next string in the distribution.
     */
    public abstract String nextString();

    /**
     * Return the previous string generated by the distribution; e.g., returned
     * from the last nextString() call. Calling lastString() should not advance
     * the distribution or have any side effects. If nextString() has not yet been
     * called, lastString() should return something reasonable.
     */
    public abstract String lastString();
}